// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type ShareKeys1 struct {
	SessionID      pgtype.UUID        `json:"session_id"`
	EncryptedShare []byte             `json:"encrypted_share"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type ShareKeys2 struct {
	SessionID      pgtype.UUID        `json:"session_id"`
	EncryptedShare []byte             `json:"encrypted_share"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}
