// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	GetShareKey1(ctx context.Context, sessionID pgtype.UUID) ([]byte, error)
	GetShareKey2(ctx context.Context, sessionID pgtype.UUID) ([]byte, error)
	InsertShareKey1(ctx context.Context, arg InsertShareKey1Params) error
	InsertShareKey2(ctx context.Context, arg InsertShareKey2Params) error
}

var _ Querier = (*Queries)(nil)
