// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: proto/tss.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MPCService_StreamMessages_FullMethodName = "/tss.MPCService/StreamMessages"
	MPCService_NotifyAction_FullMethodName   = "/tss.MPCService/NotifyAction"
)

// MPCServiceClient is the client API for MPCService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MPCServiceClient interface {
	// Stream messages between nodes for TSS protocol communication
	StreamMessages(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[TSSMessage, TSSMessage], error)
	// Notify other nodes to start keygen or signing process
	NotifyAction(ctx context.Context, in *ActionRequest, opts ...grpc.CallOption) (*ActionResponse, error)
}

type mPCServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMPCServiceClient(cc grpc.ClientConnInterface) MPCServiceClient {
	return &mPCServiceClient{cc}
}

func (c *mPCServiceClient) StreamMessages(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[TSSMessage, TSSMessage], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &MPCService_ServiceDesc.Streams[0], MPCService_StreamMessages_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[TSSMessage, TSSMessage]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MPCService_StreamMessagesClient = grpc.BidiStreamingClient[TSSMessage, TSSMessage]

func (c *mPCServiceClient) NotifyAction(ctx context.Context, in *ActionRequest, opts ...grpc.CallOption) (*ActionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ActionResponse)
	err := c.cc.Invoke(ctx, MPCService_NotifyAction_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MPCServiceServer is the server API for MPCService service.
// All implementations must embed UnimplementedMPCServiceServer
// for forward compatibility.
type MPCServiceServer interface {
	// Stream messages between nodes for TSS protocol communication
	StreamMessages(grpc.BidiStreamingServer[TSSMessage, TSSMessage]) error
	// Notify other nodes to start keygen or signing process
	NotifyAction(context.Context, *ActionRequest) (*ActionResponse, error)
	mustEmbedUnimplementedMPCServiceServer()
}

// UnimplementedMPCServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMPCServiceServer struct{}

func (UnimplementedMPCServiceServer) StreamMessages(grpc.BidiStreamingServer[TSSMessage, TSSMessage]) error {
	return status.Errorf(codes.Unimplemented, "method StreamMessages not implemented")
}
func (UnimplementedMPCServiceServer) NotifyAction(context.Context, *ActionRequest) (*ActionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NotifyAction not implemented")
}
func (UnimplementedMPCServiceServer) mustEmbedUnimplementedMPCServiceServer() {}
func (UnimplementedMPCServiceServer) testEmbeddedByValue()                    {}

// UnsafeMPCServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MPCServiceServer will
// result in compilation errors.
type UnsafeMPCServiceServer interface {
	mustEmbedUnimplementedMPCServiceServer()
}

func RegisterMPCServiceServer(s grpc.ServiceRegistrar, srv MPCServiceServer) {
	// If the following call pancis, it indicates UnimplementedMPCServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MPCService_ServiceDesc, srv)
}

func _MPCService_StreamMessages_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(MPCServiceServer).StreamMessages(&grpc.GenericServerStream[TSSMessage, TSSMessage]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MPCService_StreamMessagesServer = grpc.BidiStreamingServer[TSSMessage, TSSMessage]

func _MPCService_NotifyAction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ActionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MPCServiceServer).NotifyAction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MPCService_NotifyAction_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MPCServiceServer).NotifyAction(ctx, req.(*ActionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MPCService_ServiceDesc is the grpc.ServiceDesc for MPCService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MPCService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "tss.MPCService",
	HandlerType: (*MPCServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "NotifyAction",
			Handler:    _MPCService_NotifyAction_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamMessages",
			Handler:       _MPCService_StreamMessages_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "proto/tss.proto",
}
